name: "Terraform Multi-job Pipeline"

on:
  workflow_dispatch:  # manual trigger for full run
  push:
    branches:
      - feature/dev
      - qa
      - main

jobs:
  # =======================
  # Feature/Dev → Dev
  # =======================
  # dev:
  #   runs-on: self-hosted
  #   defaults:
  #     run:
  #       working-directory: environment/dev
  #   steps:
  #     - name: Checkout feature/dev
  #       uses: actions/checkout@v3
  #       with:
  #         ref: feature/dev

  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_SECRET_ID }}

  #     - name: Terraform Init
  #       shell: powershell
  #       run: terraform init

  #     - name: Terraform Plan
  #       shell: powershell
  #       run: terraform plan -var-file="terraform.tfvars"

  #     - name: Terraform Apply
  #       shell: powershell
  #       run: terraform apply -var-file="terraform.tfvars" -auto-approve

  # =======================
  # QA/Stage → DevSecOps + Terraform
  # =======================
   qa:
     runs-on: self-hosted
     defaults:
     run:
      working-directory: environment/qa
      steps:
       - name: Checkout qa branch
         uses: actions/checkout@v3
         with:
          ref: qa

       - name: Azure Login
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_SECRET_ID }}

    # ---------- DevSecOps Checks ----------
       - name: Add TFLint & Tfsec to PATH
         shell: powershell
         run: |
           echo "C:\tflint" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
           echo "C:\DevOpsinsider\part-1\driver\tflint_windows_amd64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

       - name: Verify DevSecOps Tools
         shell: powershell
         run: |
           tflint --version
           tfsec --version

       - name: Run TFLint
         shell: powershell
         run: tflint .

       - name: Run TFSEC
         shell: powershell
         run: tfsec .

    # ---------- Terraform ----------
       - name: Terraform Init
         shell: powershell
         run: terraform init

       - name: Terraform Plan
         shell: powershell
         run: terraform plan -var-file="terraform.tfvars"

       - name: Terraform Apply
         shell: powershell
         run: terraform apply -var-file="terraform.tfvars" -auto-approve


  # =======================
  # Main/Prod → Terraform Apply
  # =======================
   prod:
    needs: qa
    runs-on: self-hosted
    defaults:
      run:
        working-directory: environment/prod
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET_ID }}

      - name: Terraform Init
        shell: powershell
        run: terraform init

      - name: Terraform Plan
        shell: powershell
        run: terraform plan -var-file="terraform.tfvars"

      # Manual approval recommended for prod apply
      - name: Terraform Apply (Prod)
        shell: powershell
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
