name: "Terraform Multi-Stage Pipeline"

on:
  push:
    branches:
      - feature/**
      - qa/**
      - main

jobs:
  feature:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          terraform_version: 1.8.5
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_SECRET_ID }}
      - name: Terraform Init
        run: terraform init -backend-config="environment/dev/backend.tfvars"
      - name: Terraform Plan (Feature)
        run: terraform plan -var-file="environment/dev/terraform.tfvars"
      
     

