name: "Terraform Multi-Stage Pipeline"

on:
  push:
    branches:
      - feature
      - qa
      - main

jobs:
  feature:
    if: github.ref == 'refs/heads/feature'
    runs-on: self-hosted
    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure Login (using secrets)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET_ID }}

      # Step 3: Terraform Init (dev backend)
      - name: Terraform Init
        run: terraform init -backend-config="environment/dev/terraform.tfvars"

      # Step 4: Terraform Plan
      - name: Terraform Plan (Feature)
        run: terraform plan -var-file="environment/dev/terraform.tfvars"


      

      
     

