name: "jitu"

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'hotfix'

  jobs:
    terraformInit: 
    name: terraformInit
    runs-on: self-hosted
     steps:
     - name: jitu
     - run: echo Hello world!
   
