name: "Terraform Multi-job Pipeline"

on:
  workflow_dispatch:  # manual trigger for full run
  push:
    branches:
      - feature/dev
      - qa
      - main

jobs:
  # =======================
  # Feature/Dev → Dev
  # =======================
  # dev:
  #   runs-on: self-hosted
  #   defaults:
  #     run:
  #       working-directory: environment/dev
  #   steps:
  #     - name: Checkout feature/dev
  #       uses: actions/checkout@v3
  #       with:
  #         ref: feature/dev

  #     - name: Azure Login
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_SECRET_ID }}

  #     - name: Terraform Init
  #       shell: powershell
  #       run: terraform init

  #     - name: Terraform Plan
  #       shell: powershell
  #       run: terraform plan -var-file="terraform.tfvars"

  #     - name: Terraform Apply
  #       shell: powershell
  #       run: terraform apply -var-file="terraform.tfvars" -auto-approve

  # =======================
  # QA/Stage → DevSecOps + Terraform
  # =======================
  qa:
    needs: dev
    runs-on: self-hosted
    defaults:
      run:
        working-directory: environment/qa
    steps:
      - name: Checkout qa branch
        uses: actions/checkout@v3
        with:
          ref: qa

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET_ID }}

      # ---------- DevSecOps Checks ----------
      - name: Debug tflint path
        run: |
          echo "Workspace: $env:GITHUB_WORKSPACE"
          dir $env:GITHUB_WORKSPACE\tflint

      - name: Install TFLint (portable)
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://github.com/terraform-linters/tflint/releases/latest/download/tflint_windows_amd64.zip -OutFile tflint.zip
          Expand-Archive tflint.zip -DestinationPath $env:GITHUB_WORKSPACE\tflint
          $env:PATH += ";$env:GITHUB_WORKSPACE\tflint"

      - name: Run TFLint
        shell: powershell
        run: tflint

      - name: Install TFSEC (portable)
        shell: powershell
        run: |
          Invoke-WebRequest -Uri https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-windows-amd64.zip -OutFile tfsec.zip
          Expand-Archive tfsec.zip -DestinationPath $env:GITHUB_WORKSPACE\tfsec
          $env:PATH += ";$env:GITHUB_WORKSPACE\tfsec"

      - name: Run TFSEC
        shell: powershell
        run: tfsec .

      # ---------- Terraform ----------
      - name: Terraform Init
        shell: powershell
        run: terraform init

      - name: Terraform Plan
        shell: powershell
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        shell: powershell
        run: terraform apply -var-file="terraform.tfvars" -auto-approve

  # =======================
  # Main/Prod → Terraform Apply
  # =======================
  prod:
    needs: qa
    runs-on: self-hosted
    defaults:
      run:
        working-directory: environment/prod
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SECRET_ID }}

      - name: Terraform Init
        shell: powershell
        run: terraform init

      - name: Terraform Plan
        shell: powershell
        run: terraform plan -var-file="terraform.tfvars"

      # Manual approval recommended for prod apply
      - name: Terraform Apply (Prod)
        shell: powershell
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
